language: cpp
compiler: g++
sudo: required
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
    - sudo apt-get update

install:
    - sudo apt-get install qt58-meta-full
    - source /opt/qt58/bin/qt58-env.sh

script:
    - /opt/qt58/bin/qmake -project
    - /opt/qt58/bin/qmake Base32GUI/Base32GUI.pro
    - make

